Add -n option to win-add-{l,p,Q,q} to prevent selecting the next item
cmus/cmus pull request #1017
Opened 2020-12-12 21:54 UTC by pgaskin

closes #1016

2020-12-12 22:06 UTC, pgaskin reviewed
Tested `win-add-{l,p,Q,q}` from command-line/remote/keybinding/mouse-binding with/without `-n` flag.

2020-12-13 12:43 UTC, nefthy requested changes
While not incorrect, I'd prefer `advance` to `no_next` as reading the code is a bit more straightforward without the implicit negation.

2020-12-13 16:20 UTC, nefthy approved these changes

2020-12-13 16:24 UTC, pgaskin reviewed
Tested `win-add-{l,p,Q,q}` from command-line/remote/keybinding/mouse-binding with/without `-n` flag. Also tested `update-cache` to ensure it correctly moves to the next item.

2020-12-13 16:34 UTC, merged