Limit max draw width to 1023 columns
cmus/cmus pull request #1065
Opened 2021-03-25 18:56 UTC by gavtroy

Previously we allowed for 511 columns and would crash if the window was
larger than this. The browser tab had an even lower limit when the path
contained multibyte characters.

2021-03-25 19:02 UTC, gavtroy commented on ui_curses.c
> +	print_buffer[c + pad_sz] = '\0';
This small fix is not strictly related to the buffer size changes, but I realized sprintf is not multibyte aware (duh) so it won't always add enough padding in the title of the browser tab.

2021-03-26 00:59 UTC, nefthy requested changes

2021-03-26 00:59 UTC, nefthy commented on ui_curses.c
> +static char title_buffer[4096];
Im not too fond of replacing multiple local variables with a single file global variable.

2021-03-27 16:26 UTC, gavtroy commented on ui_curses.c
> +	print_buffer[c + pad_sz] = '\0';
Actually, `title` will already have been padded by `format_str()`. Let me just remove the confusing padding specifier here.

2021-03-27 16:44 UTC, nefthy approved these changes

2021-03-27 16:44 UTC, nefthy commented
LGTM

2021-04-19 19:07 UTC, merged

2021-04-19 19:07 UTC, flyingmutant commented
I somehow missed that this was ready for merge, sorry! Finally merged.